//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupViewer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Are_You_Sure.
        /// </summary>
        internal static string LOC_Are_You_Sure {
            get {
                return ResourceManager.GetString("LOC_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Are_You_Sure_You_Want_To_Change_The_Language.
        /// </summary>
        internal static string LOC_Are_You_Sure_You_Want_To_Change_The_Language {
            get {
                return ResourceManager.GetString("LOC_Are_You_Sure_You_Want_To_Change_The_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Are_You_Sure_You_Want_To_Close_The_Application.
        /// </summary>
        internal static string LOC_Are_You_Sure_You_Want_To_Close_The_Application {
            get {
                return ResourceManager.GetString("LOC_Are_You_Sure_You_Want_To_Close_The_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Attendance.
        /// </summary>
        internal static string LOC_Attendance {
            get {
                return ResourceManager.GetString("LOC_Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Away_Team.
        /// </summary>
        internal static string LOC_Away_Team {
            get {
                return ResourceManager.GetString("LOC_Away_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Busy.
        /// </summary>
        internal static string LOC_Busy {
            get {
                return ResourceManager.GetString("LOC_Busy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Cancel.
        /// </summary>
        internal static string LOC_Cancel {
            get {
                return ResourceManager.GetString("LOC_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Choose_An_Image.
        /// </summary>
        internal static string LOC_Choose_An_Image {
            get {
                return ResourceManager.GetString("LOC_Choose_An_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Confirm_Selection.
        /// </summary>
        internal static string LOC_Confirm_Selection {
            get {
                return ResourceManager.GetString("LOC_Confirm_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data.
        /// </summary>
        internal static string LOC_Data {
            get {
                return ResourceManager.GetString("LOC_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data_is_Loading.
        /// </summary>
        internal static string LOC_Data_is_Loading {
            get {
                return ResourceManager.GetString("LOC_Data_is_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data_Select_/_Config.
        /// </summary>
        internal static string LOC_Data_Select___Config {
            get {
                return ResourceManager.GetString("LOC_Data_Select_/_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data_Sources.
        /// </summary>
        internal static string LOC_Data_Sources {
            get {
                return ResourceManager.GetString("LOC_Data_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Delete.
        /// </summary>
        internal static string LOC_Delete {
            get {
                return ResourceManager.GetString("LOC_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Download.
        /// </summary>
        internal static string LOC_Download {
            get {
                return ResourceManager.GetString("LOC_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Download_Failed.
        /// </summary>
        internal static string LOC_Download_Failed {
            get {
                return ResourceManager.GetString("LOC_Download_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Download_State.
        /// </summary>
        internal static string LOC_Download_State {
            get {
                return ResourceManager.GetString("LOC_Download_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Error.
        /// </summary>
        internal static string LOC_Error {
            get {
                return ResourceManager.GetString("LOC_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Errors_Detected.
        /// </summary>
        internal static string LOC_Errors_Detected {
            get {
                return ResourceManager.GetString("LOC_Errors_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Errors_Detected_in_Data.
        /// </summary>
        internal static string LOC_Errors_Detected_in_Data {
            get {
                return ResourceManager.GetString("LOC_Errors_Detected_in_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Failed_to_Load_Data.
        /// </summary>
        internal static string LOC_Failed_to_Load_Data {
            get {
                return ResourceManager.GetString("LOC_Failed_to_Load_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Failed_To_Load_Settings_Data_Will_Not_Be_Saved.
        /// </summary>
        internal static string LOC_Failed_To_Load_Settings_Data_Will_Not_Be_Saved {
            get {
                return ResourceManager.GetString("LOC_Failed_To_Load_Settings_Data_Will_Not_Be_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Failed_To_Save_Settings.
        /// </summary>
        internal static string LOC_Failed_To_Save_Settings {
            get {
                return ResourceManager.GetString("LOC_Failed_To_Save_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Favourites.
        /// </summary>
        internal static string LOC_Favourites {
            get {
                return ResourceManager.GetString("LOC_Favourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Games_Captained.
        /// </summary>
        internal static string LOC_Games_Captained {
            get {
                return ResourceManager.GetString("LOC_Games_Captained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Goals_Scored.
        /// </summary>
        internal static string LOC_Goals_Scored {
            get {
                return ResourceManager.GetString("LOC_Goals_Scored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Guid_Error_Data_Might_Not_Be_Saved.
        /// </summary>
        internal static string LOC_Guid_Error_Data_Might_Not_Be_Saved {
            get {
                return ResourceManager.GetString("LOC_Guid_Error_Data_Might_Not_Be_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Home_Team.
        /// </summary>
        internal static string LOC_Home_Team {
            get {
                return ResourceManager.GetString("LOC_Home_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Info.
        /// </summary>
        internal static string LOC_Info {
            get {
                return ResourceManager.GetString("LOC_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Load.
        /// </summary>
        internal static string LOC_Load {
            get {
                return ResourceManager.GetString("LOC_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Local.
        /// </summary>
        internal static string LOC_Local {
            get {
                return ResourceManager.GetString("LOC_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Matches_By_Attendance.
        /// </summary>
        internal static string LOC_Matches_By_Attendance {
            get {
                return ResourceManager.GetString("LOC_Matches_By_Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Name.
        /// </summary>
        internal static string LOC_Name {
            get {
                return ResourceManager.GetString("LOC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_No.
        /// </summary>
        internal static string LOC_No {
            get {
                return ResourceManager.GetString("LOC_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Okay.
        /// </summary>
        internal static string LOC_Okay {
            get {
                return ResourceManager.GetString("LOC_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Player_Data_is_Loading.
        /// </summary>
        internal static string LOC_Player_Data_is_Loading {
            get {
                return ResourceManager.GetString("LOC_Player_Data_is_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Player_List.
        /// </summary>
        internal static string LOC_Player_List {
            get {
                return ResourceManager.GetString("LOC_Player_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Players.
        /// </summary>
        internal static string LOC_Players {
            get {
                return ResourceManager.GetString("LOC_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Players_By_Goals_Scored.
        /// </summary>
        internal static string LOC_Players_By_Goals_Scored {
            get {
                return ResourceManager.GetString("LOC_Players_By_Goals_Scored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Players_By_Yellow_Cards.
        /// </summary>
        internal static string LOC_Players_By_Yellow_Cards {
            get {
                return ResourceManager.GetString("LOC_Players_By_Yellow_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Ready.
        /// </summary>
        internal static string LOC_Ready {
            get {
                return ResourceManager.GetString("LOC_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Remote.
        /// </summary>
        internal static string LOC_Remote {
            get {
                return ResourceManager.GetString("LOC_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Selected_Team.
        /// </summary>
        internal static string LOC_Selected_Team {
            get {
                return ResourceManager.GetString("LOC_Selected_Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Shirt_Number.
        /// </summary>
        internal static string LOC_Shirt_Number {
            get {
                return ResourceManager.GetString("LOC_Shirt_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Structure.
        /// </summary>
        internal static string LOC_Structure {
            get {
                return ResourceManager.GetString("LOC_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Team_Slash_Player_Select.
        /// </summary>
        internal static string LOC_Team_Slash_Player_Select {
            get {
                return ResourceManager.GetString("LOC_Team_Slash_Player_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Team_Statistics.
        /// </summary>
        internal static string LOC_Team_Statistics {
            get {
                return ResourceManager.GetString("LOC_Team_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_The_Following_Errors_Have_Been_Detected_while_Loading_Data.
        /// </summary>
        internal static string LOC_The_Following_Errors_Have_Been_Detected_While_Loading_Data {
            get {
                return ResourceManager.GetString("LOC_The_Following_Errors_Have_Been_Detected_While_Loading_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Usual_Position.
        /// </summary>
        internal static string LOC_Usual_Position {
            get {
                return ResourceManager.GetString("LOC_Usual_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Wait.
        /// </summary>
        internal static string LOC_Wait {
            get {
                return ResourceManager.GetString("LOC_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Year.
        /// </summary>
        internal static string LOC_Year {
            get {
                return ResourceManager.GetString("LOC_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Yellow_Cards.
        /// </summary>
        internal static string LOC_Yellow_Cards {
            get {
                return ResourceManager.GetString("LOC_Yellow_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Yes.
        /// </summary>
        internal static string LOC_Yes {
            get {
                return ResourceManager.GetString("LOC_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Yes_And_Do_Not_Ask_Again.
        /// </summary>
        internal static string LOC_Yes_And_Do_Not_Ask_Again {
            get {
                return ResourceManager.GetString("LOC_Yes_And_Do_Not_Ask_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Test.
        /// </summary>
        internal static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Test2.
        /// </summary>
        internal static string TestString2 {
            get {
                return ResourceManager.GetString("TestString2", resourceCulture);
            }
        }
    }
}
