//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldCupViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldCupViewer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data.
        /// </summary>
        internal static string LOC_Data {
            get {
                return ResourceManager.GetString("LOC_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data_Select_/_Config.
        /// </summary>
        internal static string LOC_Data_Select___Config {
            get {
                return ResourceManager.GetString("LOC_Data_Select_/_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Data_Sources.
        /// </summary>
        internal static string LOC_Data_Sources {
            get {
                return ResourceManager.GetString("LOC_Data_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Delete.
        /// </summary>
        internal static string LOC_Delete {
            get {
                return ResourceManager.GetString("LOC_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Error.
        /// </summary>
        internal static string LOC_Error {
            get {
                return ResourceManager.GetString("LOC_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Info.
        /// </summary>
        internal static string LOC_Info {
            get {
                return ResourceManager.GetString("LOC_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Load.
        /// </summary>
        internal static string LOC_Load {
            get {
                return ResourceManager.GetString("LOC_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Local.
        /// </summary>
        internal static string LOC_Local {
            get {
                return ResourceManager.GetString("LOC_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Okay.
        /// </summary>
        internal static string LOC_Okay {
            get {
                return ResourceManager.GetString("LOC_Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Remote.
        /// </summary>
        internal static string LOC_Remote {
            get {
                return ResourceManager.GetString("LOC_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Structure.
        /// </summary>
        internal static string LOC_Structure {
            get {
                return ResourceManager.GetString("LOC_Structure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOC_Wait.
        /// </summary>
        internal static string LOC_Wait {
            get {
                return ResourceManager.GetString("LOC_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Test.
        /// </summary>
        internal static string TestString {
            get {
                return ResourceManager.GetString("TestString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Test2.
        /// </summary>
        internal static string TestString2 {
            get {
                return ResourceManager.GetString("TestString2", resourceCulture);
            }
        }
    }
}
